sugarcrm/debezium

- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbChangeEventSourceFactory.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbConnectorTask.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSnapshotChangeEventSource.java
- debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbStreamingChangeEventSource.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/EventBuffer.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlChangeEventSourceFactory.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSnapshotChangeEventSource.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java
- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/legacy/MySqlConnectorTask.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresChangeEventSourceFactory.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSnapshotChangeEventSource.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerChangeEventSourceFactory.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSnapshotChangeEventSource.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
- debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
- debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java
- debezium-core/src/main/java/io/debezium/pipeline/source/AbstractSnapshotChangeEventSource.java
- debezium-core/src/main/java/io/debezium/pipeline/source/spi/ChangeEventSourceFactory.java
- debezium-core/src/main/java/io/debezium/pipeline/source/spi/SnapshotChangeEventSource.java
- debezium-core/src/main/java/io/debezium/pipeline/source/spi/StreamingChangeEventSource.java
- debezium-core/src/main/java/io/debezium/pipeline/spi/SnapshotResult.java
- debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
Closes #8.
It should be possible to reuse the graph of components under `ChangeEventSourceCoordinator` for processing multiple partitions represented via `OffsetContext` sequentially. Specifically, `StreamingChangeEventSource#execute()` and `SnapshotChangeEventSource#execute()` should accept an offset context and explicitly pass it down the line.
The following classes and hierarchies no longer have the offset context as part of their state which is now part of their interface:
1. `ChangeEventSourceFactory` (including all connector implementations).
2. `SnapshotChangeEventSource` (including snapshot/streaming interfaces and all connector implementations).
3. Connector-specific classes (`mysql.EventBuffer`).
Certain classes are parametrized with `<O extends OffsetContext`>. Since the graph …
> DBZ-2975: Extract offset context from object states to method signatures

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlOffsetContext.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresOffsetContext.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorTask.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerOffsetContext.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerTaskPartition.java
- debezium-core/src/main/java/io/debezium/connector/common/TaskOffsetContext.java
- debezium-core/src/main/java/io/debezium/connector/common/TaskPartition.java
- debezium-core/src/main/java/io/debezium/pipeline/spi/OffsetContext.java
Closes #12. The corresponding [section](https://gist.github.com/morozov/1157990ccd7ca00ca89637da914a4c08#source-partition-awareness-at-the-task-level-15) of the design doc.
**Change summary**:
1. `OffsetContext.Loader` is parametrized with `<O extends OffsetContext>` (see https://github.com/sugarcrm/debezium/pull/13 for the reasoning).
2. All messages produced by the SQL Server connector instead of having "server=serverName" as their source partition now have "server=serverName;database=databaseName" as their source partition. This is a breaking change from the PoV of existing users. An existing connector upgraded to this version won't be able to recover from the state produced by the previous version.
**New APIs**:
1. `TaskPartition` interface. Describes the partition of the source to be …
> DBZ-2975: Prototype multiple offset contexts per task

- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/AbstractSqlServerDatatypesTest.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/CaseSensitivenessIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/EventProcessingFailureHandlingIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SQLServerNumericColumnIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SchemaHistoryTopicIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SnapshotIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SnapshotWithSelectOverridesIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SpecialCharsInNamesIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerBinaryModeIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerChangeTableSetIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectionIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorTransactionIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/TablesWithoutPrimaryKeyIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/TransactionMetadataIT.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java
- debezium-connector-sqlserver/src/test/resources/generate_cdc_wrappers.sql
**TODO:**
**FAILING TESTS** (probably a bug in our code):
- `SqlServerConnectorIT.testBlacklistTable`
- `SqlServerConnectorIT.testTableExcludeList`
> DBZ-2975: Integration testing

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerOffsetContext.java
The absence of this condition leads to sporadic [test](https://github.com/sugarcrm/debezium/pull/42/checks?check_run_id=2365676888#step:4:5097) [failures](https://github.com/sugarcrm/debezium/pull/43/checks?check_run_id=2364855269#step:4:5050) caused by a `NullPointerException`:
```
java.lang.NullPointerException
at io.debezium.connector.sqlserver.SqlServerOffsetContext.eventsStreamed(SqlServerOffsetContext.java:225)
at io.debezium.pipeline.spi.StreamingResult.eventsStreamed(StreamingResult.java:21)
at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:150)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at …
```
> DBZ-2975: Fix inconsistent test failure due NullPointerException

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SourceTimestampMode.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerChangeTablePointer.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
Documented as [DBZ-3452](https://issues.redhat.com/browse/DBZ-3452).
**Future scope**:
> [...] avoid the additional cost of Debezium querying the database to extract the LSN timestamps.
> DBZ-3452: source.timestamp.mode=commit imposes a significant performance penalty

- debezium-core/src/main/java/io/debezium/relational/history/AbstractDatabaseHistory.java
```java
import java.util.*;
class Main {  
public static void main(String args[]) {
List<String> ddls = Arrays.asList(
"a tO b", "a \nto b ",
"\ta   TO  b\n",
" ab \nc to d ",
"`db_novel`.`users`\n                  TO `db_novel`.`users_updated`",
"`db_ths`.`tasks`\n                  TO `db_ths`.`tasks_old`"
);
for (String ddl : ddls) {
String fixedDdl = ddl.replaceAll("\\s+", " ").trim();
if (!fixedDdl.matches("(?i)^[\\w\\.`]+ TO [\\w\\.`]+$")) {
System.out.println("ERROR: " + ddl);
continue;
}
System.out.println("RENAME TABLE " + fixedDdl);
}
} 
}
```
```sh
RENAME TABLE a tO b
RENAME TABLE a to b
RENAME TABLE a TO b
ERROR:  ab 
c to d 
RENAME TABLE `db_novel`.`users` TO `db_novel`.`users_updated`
RENAME TABLE `db_ths`.`tasks` TO `db_ths`.`tasks_old`
```
> CXP-1093: allow "." and "`" characters

- debezium-core/src/main/java/io/debezium/util/SchemaNameAdjuster.java
The approach with a NULL implementation didn't work because there is still a static API (e.g. `SchemaNameAdjuster#isValidFullname(String)`) that connectors call to validate the resulting schema name. It would have to be removed as well.
Instead, we can just replace the exception with a warning. Unlike AVRO, where the schema name is a pointer to the actual schema in the registry, with JSON serialization it's just for reference and doesn't have to be unique (technically, could be even omitted).
> [CXP-1130] Schema name conflict between foo-case12345 and foo_case12345 tables

- debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlDefaultValueTest.java
- debezium-core/src/main/java/io/debezium/jdbc/JdbcValueConverters.java
It looks like MySQL rounds the default value internally:
```sql
CREATE TABLE `foo15` (
id INTEGER DEFAULT '1.5'
);
SHOW CREATE TABLE foo15;
-- CREATE TABLE `foo15` (
--   `id` int(11) DEFAULT '2'
-- )
```
> DBZ-3541: Parse integer default value as float and round

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
If I correctly understand how 1:M connector works here’s what is happening: `io.debezium.pipeline.ChangeEventSourceCoordinator#start` calls `io.debezium.pipeline.ChangeEventSourceCoordinator#streamEvents` in a loop for each database until there are some cdc in at least one database. Then it sleeps and repeats `streamEvents` calls. Each call to `streamEvents` calls `io.debezium.connector.sqlserver.SqlServerStreamingChangeEventSource#execute` which calls `io.debezium.connector.sqlserver.SqlServerStreamingChangeEventSource#getCdcTablesToQuery` in the beginning:
https://github.com/sugarcrm/debezium/blob/e876745208ae303b892245955b37c9f8f6a22634/debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java#L106
Therefore the stored procedure …
> CXP-1127: 1:M SQL Server connectors create extensive load on the database server

- debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java
This is an attempt to mitigate the idle connection timeout. The connector will disconnect before schema recovery and reconnect afterward. This approach has been verified in k8s-usw2-dev using the following patch: https://github.com/sugarcrm/debezium/blob/64ca504ef4e935a5b3d0fc014c4d357a4a9f22df/debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorTask.java#L96-L119
The logs in the worker pod would look like the following:
```
{
"@timestamp": "2021-05-28T20:32:54.936Z",
"source_host": "cxp-connect-connect-7bfc7465c8-8hkw4",
"file": "MySqlConnectorTask.java",
"method": "start",
"level": "ERROR",
"line_number": "96",
"thread_name": "task-thread-cxp-demo-us-west-2-609981f76d6333715470ed29-cdc-source-0",
"@version": 1,
"logger_name": …
```
> DBZ-0000: [CXP-1145] Disconnect before schema recovery

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerChangeTableSetIT.java
Currently if we limit the number of LSNs per iteration (`max.iteration.transactions`) we do it only for queries responsible for fetching cdc data from capture instance tables. While the list of capture instances itself is not filtered. So when a schema change happens cdc queries are prepared for capture instances not belonging to the current LSN interval.
It's not a big problem on its own. But internally our LSN interval is modified per each capture instance table resulting to invalid intervals and finally errors from SQL Server. 
```
CI  |                                                                LSNs      
-------------------------------------------------------------------------->
ci1 |  A                    B
|  |--------------------|
|
ci2 |           C                      D
| …
```
> CXP-1337: Filter out invalid LSNs 

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerErrorHandler.java
Depending on the 1:1 or the 1:M mode, either of the errors can occur when the database is in transition.
> [CXP-1546] SQL Server connector fails during a database transition into read-only mode

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerChangeTable.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSnapshotChangeEventSource.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectionIT.java
1. Revert the logic implemented in #97, since the comparison by `create_date` is now implemented in SQL.
2. Filter out duplicates in SQL. This will eliminate the need to implement this logic in multiple places on the client side where this comparison wasn't implemented by the previous patch.
3. Try not to select `end_lsn` since it's always NULL ([ref](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sys-sp-cdc-help-change-data-capture-transact-sql?view=sql-server-2016#result-sets)). The existing logic that relies on it must be redundant.
4. Do not filter capture instances by `end_lsn` since it's always NULL.
> [CXP-1553] Filter out capture instances with the same start_lsn

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerErrorHandler.java
From the [documentation](https://docs.microsoft.com/en-us/sql/relational-databases/errors-events/database-engine-events-and-errors?view=sql-server-ver15):
| Error  | Description |
| ------------- | ------------- |
| 18401  | Login failed for user '%.*ls'. Reason: Server is in script upgrade mode. Only administrator can connect at this time.%.*ls |
> [CXP-1554] Handle error 18401 "Login failed for user..." as retriable

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
The "No maximum LSN recorded ..." log message will spam the log in production on databases with low or no activity. This is due to the `getNthTransactionLsnFromLast` being used to retrieve the `toLsn`. During low activity this call will return `NULL` resulting in this message being emitted.
> [CXP-1566] Change "No maximum LSN recorded" log message to debug level

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerChangeEventSourceFactory.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerSnapshotProgressDatabaseCallbacks.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingProgressDatabaseCallbacks.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingProgressListener.java
- debezium-core/src/main/java/io/debezium/pipeline/source/spi/SnapshotProgressListenerList.java
- debezium-core/src/main/java/io/debezium/pipeline/source/spi/StreamingProgressListener.java
This change creates two new classes `SqlServerStreamingProgressDatabaseCallbacks` and `SqlServerSnapshotProgressDatabaseCallbacks` that implement the `SnapshotProgressListener` and the new `StreamingProgressListener` and `SqlServerStreamingProgressListener` interfaces. These new classes are intended for calling stored procedures or CRUD necessary for calling back to the database during snapshot or streaming events as they occur. An example would be when a new capture instance starts being read.
> [CXP-1523] Call back to the database for streaming and snapshot progress events.

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
Change the `database.callbacks` option to a non-internal configuration parameter and increase the log level for the database callbacks.
> [CXP-1523] Call back to the database for snapshot progress events.

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingExecutionContext.java
The previous version of the feature was tracked in [sugarcrm-jgminder/1.9.2-database-callbacks](https://github.com/sugarcrm-jgminder/debezium/tree/1.9.2-database-callbacks).
TODO:
> CXP-2071: [SPIKE] Refactor schema change handling callbacks to use committed offsets

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerErrorHandler.java
Before this is merged, the following patches have been [applied](https://sugarcrm.slack.com/archives/C01AELD28BT/p1666825793083489?thread_ts=1666775819.052149&cid=C01AELD28BT) to the connectors:
```shell
kubectl --context k8s-usw2-prod -n cxp patch kctr market.use1-mssql-01 \
--type=json \
-p '[{
"op":"add",
"path":"/spec/config/custom.retriable.exception",
"value":"Cannot continue the execution because the session is in the kill state\\."
}]'
kubectl --context k8s-usw2-prod -n cxp patch kctr market.use1-mssql-03 \
--type=json \
-p '[{
"op":"add",
"path":"/spec/config/custom.retriable.exception",
"value":"Cannot continue the execution because the session is in the kill state\\."
}]'
```
> CXP-2278: Handle another SQL Server error as retriable

- debezium-core/src/main/java/io/debezium/relational/history/KafkaDatabaseHistory.java
JIRA: [DBZ-5855](https://issues.redhat.com/browse/DBZ-5855)
**TODO:**
> DBZ-5855: IllegalStateException is thrown if task is recovering while other tasks are running

- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/SqlServerConnectorIT.java
The problem of permanent errors scoped to a single database blocking capturing changes from others existed only prior to https://github.com/sugarcrm/debezium/pull/133 since the task would restart infinitely and never reach the databases after the one causing the failure.
The logic implemented there behaves as expected and increases the restart counter during each failure unless at least one streaming iteration was successfully completed for _all_ databases processed by the task before the failure. It wasn't obvious to me at the time of filing the issue.
This PR extends the previously added test to cover both the snapshotting failure and streaming failure scenarios. It also removes the "non-existing-database" database from the test configuration as it seems copied from another test and is …
> CXP-2351: Test restart due to streaming failure

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
To prevent deadlock exceptions the transaction needs to be committed to release locks as soon as possible:
```
[2023-02-27 15:57:03,484] ERROR [debezium-connector-sqlserver|task-0] Producer failure (io.debezium.pipeline.ErrorHandler:38)
com.microsoft.sqlserver.jdbc.SQLServerException: Transaction (Process ID 454) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
at com.microsoft.sqlserver.jdbc.SQLServerResultSet$FetchBuffer.nextRow(SQLServerResultSet.java:5479)
at com.microsoft.sqlserver.jdbc.SQLServerResultSet.fetchBufferNext(SQLServerResultSet.java:1798)
at com.microsoft.sqlserver.jdbc.SQLServerResultSet.next(SQLServe …
```
> CXP-2452: Commit the transaction right after a capture instance deletion

- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
- debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerStreamingChangeEventSource.java
- debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/DatabaseCallbacksIT.java
Squashed commit of the following:
commit 3d3f37b08509b33dda1988172bafbb2fc64cb3bf
Merge: de92a0465 48e250a7a
Author: Vadzim Ramanenka <vramanenka@sugarcrm.com>
Date:   Mon Feb 27 23:35:11 2023 +0300
Merge pull request #141 from ramanenka/CXP-2452-commit-after-ci-deletion
CXP-2452: Commit the transaction right after a capture instance deletion
commit 48e250a7a4135d8786508ac3cb4d87b97f12f4c3
Author: Vadzim Ramanenka <vramanenka@sugarcrm.com>
Date:   Mon Feb 27 18:24:55 2023 +0100
CXP-2452: Commit the transaction right after a capture instance deletion
commit de92a0465f71ff6392080da85bf2a000516272db
Author: Vadzim Ramanenka <vramanenka@sugarcrm.com>
Date:   Fri Jan 13 17:26:19 2023 +0100
CXP-2369: Execute the stored procedure using metadata connection
commit …
> CXP-1742: Merge sqlserver database callbacks
